name: Daily News Digester

on:
  schedule:
    - cron: '0 1 * * *'  # 每天台灣上午9點執行
  workflow_dispatch:     # 手動執行也支援

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      LINE_TOKEN: ${{ secrets.LINE_TOKEN }}
      LINE_USER_ID: ${{ secrets.LINE_USER_ID }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        run: python check_ticket.py
